#!/usr/bin/env python3
#
# A hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
import sys

# Read passed message through argument.
messageFile = sys.argv[1]
file = open(messageFile, 'r')
message = file.read().split("\n")
subject = message[0]
subject_length = len(subject)
if (len(message) > 2) & (message[1] != ''):
  # Subject & body should separate with a blank line.
  print("Err: Separate subject from body with a blank line")
  exit(1)
elif subject_length > 50:
  # Message subject line length should not be more than 50.
  print("Err: Limit the commit subject line to 50 characters")
  print("Current subject line count is: ", subject_length)
  exit(1)
elif subject[0].islower():
  # The first character must be uppercase.
  print("Err: Capitalize the commit subject line")
  exit(1)
elif subject[-1] == '.':
  print("Err: Do not end the commit subject line with a period")
  exit(1)
else:
  exit(0)
